name: tugaslayoubank
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Ubah ke rentang yang lebih luas untuk Flutter 3.x dan Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  url_launcher: any # Biarkan Flutter memilih versi terbaru
  shared_preferences: any # Biarkan Flutter memilih versi terbaru
  provider: any # Biarkan Flutter memilih versi terbaru
  qr_code_scanner: any # Versi 1.x.x memiliki perbaikan namespace
  intl: any # Versi 0.20.2 atau lebih baru
  mobile_scanner: any # Versi 7.x.x atau lebih baru memiliki perbaikan namespace
  permission_handler: any # Versi 12.x.x atau lebih baru
  # font_awesome_flutter: any # Ini seharusnya ada di dev_dependencies, bukan dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any # Biarkan Flutter memilih versi terbaru (seharusnya 6.x.x)
  font_awesome_flutter: any # Pindahkan ke dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/candra.jpg
    - assets/foto candraa.jpg # Perbaiki penggunaan underscore